import {
  truncateTodoTitle,
  type ParsedTodoItem,
  type TodoStatus,
} from "./todos";

/**
 * Issues a repository keeps in beads, read from the export it commits
 * (Phase 4 Wave D todo 21).
 *
 * Beads keeps its issues in Dolt and writes a JSON-lines export into
 * `.beads/`. That export is the only part of it in the git tree, so it is
 * the only part a scan can see — a repository running beads without
 * committing the export has no todos here, and that is a fact about the
 * commit rather than a gap in the reader. Nothing in this file talks to
 * beads; it reads a file that is already there.
 *
 * The difference from a checkbox is identity. A markdown item is identified
 * by a hash of its title because a document offers nothing better, so
 * retitling one loses the old todo; a beads issue carries its own id, which
 * survives a retitle, a reorder and a move between files. So the key is that
 * id, and the line number is only ever the span.
 */

/** `.beads/issues.jsonl`, at the root or under any directory. */
const BEADS_EXPORT_PATTERN = /(?:^|\/)\.beads\/[^/]+\.jsonl$/i;

export function isBeadsExportPath(path: string): boolean {
  return BEADS_EXPORT_PATTERN.test(path.replaceAll("\\", "/"));
}

/**
 * Beads' states, and the two spellings its export has used.
 *
 * An unrecognised state reads as `open`. `TodoStatus` has no "unknown", and
 * `open` is the only one of the four that claims nothing beyond "not
 * finished" — reading a state we do not know as `done` would report work as
 * complete on the strength of a word we failed to parse.
 */
const STATUS_BY_BEADS_STATE: Readonly<Record<string, TodoStatus>> = {
  blocked: "blocked",
  closed: "done",
  done: "done",
  "in-progress": "in-progress",
  in_progress: "in-progress",
  open: "open",
};

function statusOf(value: unknown): TodoStatus {
  return typeof value === "string"
    ? (STATUS_BY_BEADS_STATE[value.trim().toLowerCase()] ?? "open")
    : "open";
}

function textOf(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const text = value.replace(/\s+/g, " ").trim();
  return text.length === 0 ? null : text;
}

export function beadsSourceKey(input: {
  readonly id: string;
  readonly path: string;
}): string {
  return `beads:${input.path}:${input.id}`;
}

/**
 * Read a beads export. A line that is blank, is not a JSON object, or names
 * neither an id nor a title is skipped rather than failing the scan: this
 * file is generated by another tool, and one line it wrote in a shape we do
 * not know is not a reason to lose the rest of a repository's issues.
 *
 * There is no cap on issues. The scan already bounds the file it reads by
 * size, and a second, invisible limit here would make todos disappear from
 * the middle of a repository's list with nothing to point at.
 */
export function parseBeadsExport(input: {
  readonly path: string;
  readonly source: string;
}): ParsedTodoItem[] {
  const items: ParsedTodoItem[] = [];
  const seen = new Set<string>();
  const lines = input.source.split("\n");
  let startByte = 0;

  for (const [index, line] of lines.entries()) {
    const lineBytes = Buffer.byteLength(line, "utf8");
    const lineStart = startByte;
    // The newline the split removed still occupies the file.
    startByte += lineBytes + 1;

    const trimmed = line.trim();
    if (trimmed.length === 0) continue;
    let parsed: unknown;
    try {
      parsed = JSON.parse(trimmed);
    } catch {
      continue;
    }
    if (
      typeof parsed !== "object" ||
      parsed === null ||
      Array.isArray(parsed)
    ) {
      continue;
    }
    const record = parsed as Record<string, unknown>;
    const id = textOf(record["id"]);
    const title = textOf(record["title"]);
    // An issue with no id has no identity to preserve, and one with no title
    // says nothing a reader could act on. Either way it is not a todo.
    if (id === null || title === null) continue;
    // A duplicated id is the export's own contradiction: keep the first,
    // which is the one an append-only export wrote first.
    if (seen.has(id)) continue;
    seen.add(id);

    items.push({
      // Beads' dependencies are edges, not nesting: `blocked_by` says what
      // must happen first, never that this issue is part of that one.
      // Flattening them into `parentKey` would put a claim in the graph that
      // beads never made.
      parentKey: null,
      source: {
        kind: "document",
        path: input.path,
        span: {
          endByte: lineStart + lineBytes,
          endColumn: line.length + 1,
          endLine: index + 1,
          path: input.path,
          startByte: lineStart,
          startColumn: 1,
          startLine: index + 1,
        },
      },
      sourceKey: beadsSourceKey({ id, path: input.path }),
      status: statusOf(record["status"]),
      title: truncateTodoTitle(title),
    });
  }

  return items;
}
