/**
 * Korean-first copy policy (ADR-009-3 / Phase 2A todo 3).
 *
 * UI copy is Korean. The terms below stay in English because they are the
 * conventional form Korean developers already read and write — translating them
 * would make the product harder to scan, not easier. Everything else must be
 * Korean; `tests/korean-strings.test.ts` enforces both halves of that rule.
 */

export const CONVENTIONAL_ENGLISH_TERMS = [
  // Product + surfaces
  "Arr",
  /** Brand tagline — an asset, not copy (ADR-008). */
  "Proof, before merge.",
  "Dark",
  "Light",
  "Dashboard",
  "Graph",
  "Findings",
  "Receipt",
  "Receipts",
  "Data Brain",
  "Inspector",
  "Live",
  // Evidence vocabulary — the verified/inferred split is product identity.
  "verified",
  "inferred",
  "broken",
  "open",
  "resolved",
  "blocked",
  "confidence",
  "stale",
  "critical",
  "high",
  "medium",
  "moderate",
  "low",
  "info",
  // Dependency-audit ingestion (Phase 2B todo 8) — the npm audit vocabulary
  // developers already read verbatim.
  "npm audit",
  "append-only",
  "major",
  "patch",
  // Keyboard key names render verbatim (OQ-006 hit-layer affordance).
  "Enter",
  // Team vocabulary (ADR-011): role names are the product's own identifiers
  // and the metric family has a fixed name.
  "admin",
  "member",
  "viewer",
  "receipt",
  "VIBE Index",
  "VIBE",
  "A/B",
  "ADR",
  // Platform + protocol
  "MCP",
  "GitHub",
  "GitHub App",
  "GitHub Actions",
  "CI",
  "CLI",
  "Git",
  "commit",
  "push",
  "SHA-256",
  "in-toto",
  "Statement",
  "digest",
  "token",
  "tokens",
  "log_progress",
  "search_index",
  "get_artifact",
  "request_context_pack",
  "AGENTS.md",
  "CLAUDE.md",
  "TODO",
  "todo",
  "Todo",
  "contents:read",
  "checks:read",
  "actions:read",
  "metadata:read",
  "pull_requests:write",
  "contents:write",
  "cl100k_base",
  // Phase 2A todo 8 — vocabulary the remaining screens need (harness, library,
  // settings, stats, auth, onboarding, evidence detail).
  "OAuth",
  "BYOK",
  "API",
  "JSON",
  "PR",
  "Pull Request",
  "diff",
  "Anthropic",
  "OpenAI",
  "Claude Code",
  "Codex",
  "Cursor",
  "Skills",
  "SKILL.md",
  "Plugins",
  "Onboarding",
  "Harness",
  "Library",
  "Settings",
  "Stats",
  "Progress",
  "workspace",
  "Workspace",
  "provenance",
  "span",
  "spans",
  "orphan",
  "sha256",
  "UTC",
  "credit",
  "credits",
  "JUnit",
  "Vitest",
  "TypeScript",
  "main",
  "declares",
  "implements",
  "references",
  "tests",
  "snapshot",
  "tag",
  "tags",
] as const;

export type ConventionalEnglishTerm =
  (typeof CONVENTIONAL_ENGLISH_TERMS)[number];
